<center>
<img src="https://supportvectors.ai/logo-poster-transparent.png" width="400px" style="opacity:0.7">
</center>

# Numpy Neural Network

In [1]:
%run supportvectors-common.ipynb


<div style="color:#aaa;font-size:8pt">
<hr/>
&copy; SupportVectors. All rights reserved. <blockquote>This notebook is the intellectual property of SupportVectors, and part of its training material. 
Only the participants in SupportVectors workshops are allowed to study the notebooks for educational purposes currently, but is prohibited from copying or using it for any other purposes without written permission.

<b> These notebooks are chapters and sections from Asif Qamar's textbook that he is writing on Data Science. So we request you to not circulate the material to others.</b>
 </blockquote>
 <hr/>
</div>



In [2]:
import numpy as np
from week_3.approximator.simple_neural_network import SimpleNeuralNetwork

Generate 1000 points uniformly in the range of [0,1] and apply the below mathematical function to them
$$ y = 4x^2 + 11x + 3 $$

In [3]:
# Generate 1000 points uniformly spread out in the range [0, 1]
x = np.linspace(0, 1, 1000).reshape(-1, 1)

# Calculate y = 4x^2 + 11x + 3
y = 4 * x**2 + 11 * x + 3


Now initialize and train a simple neural network that is based on numpy (not on any autograd framework)

In [4]:

# Initialize and train the neural network
nn = SimpleNeuralNetwork()
nn.train(x, y, epochs=100, learning_rate=0.0001)


epoch: 0: loss: [13.93380894]
epoch: 20: loss: [0.37805529]
epoch: 40: loss: [0.77336452]
epoch: 60: loss: [0.77775073]
epoch: 80: loss: [0.7777879]


Now test this network on some sample points

In [6]:

# Test the network

x_sample = np.array([0.2, 0.8, 0.4, 0.9]).reshape(-1, 1)
y_sample = 4 * x_sample**2 + 11*x_sample + 3
output_sample = nn.forward(x_sample)
print(f"Input being tested:\n {x_sample}")
print(f"Expected output:\n {y_sample}")
print(f"Predicted output:\n {output_sample}")

Input being tested:
 [[0.2]
 [0.8]
 [0.4]
 [0.9]]
Expected output:
 [[ 5.36]
 [14.36]
 [ 8.04]
 [16.14]]
Predicted output:
 [[ 5.23957354]
 [14.60405798]
 [ 8.36106835]
 [16.16480538]]
